% Plots dot plots for concussion paper (results fig 1)

clc;clear;close all;

SHOW_SCAT_SUM = false;
SHOW_SCAT_COUNT = false;
SHOW_DAYS_POST_INJRY = false;

SHOW_RAW = false;
SHOW_TRANSFORMED = true;

SHOW_TIMING = true;
SHOW_ACCURACY = true;

SHOW_SUBIDS = true;


data = load('MasterTable.mat');
data = data.MasterTable;
data = data(data.DidComplete & data.Session == 1, :);
data(data.SubID=="C019", :) = [];
% Remove ACC data from invalid sessions
data{data.SubID=="N018", ["c_DET_Acc_asr", "c_DET_Acc_per"]} = NaN;
data{data.SubID=="N013", ["c_ONB_Acc_asr", "c_ONB_Acc_per"]} = NaN;
data{data.SubID=="C005", ["c_IDN_Acc_asr", "c_IDN_Acc_per"]} = NaN;

if SHOW_RAW
	if SHOW_TIMING
		RobotResults2.PlotDotLine(data, ...
			"c_" + ["DET", "IDN", "ONB", "OCL"]' + "_Spd_ms", ...
			data.Session == 1, ...
			"VarNames", ["DET", "IDN", "ONB", "OCL"],...
			"Title", "CogState Timing Measures",...
			"XLabel", "Reaction Time (ms)",...
			"ShowCompZScore",true,...
			"ShowRaw",true,...
			"ShowZScore",true,...
			"ShowSubIDs",SHOW_SUBIDS)
	end
	if SHOW_ACCURACY
		RobotResults2.PlotDotLine(data, ...
			"c_" + ["DET", "IDN", "ONB", "OCL"]' + "_Acc_per", ...
			data.Session == 1, ...
			"VarNames", ["DET", "IDN", "ONB", "OCL"],...
			"Title", 'CogState Accuracy Measures',...
			"XLabel", "Response Accuracy % Correct",...
			"ShowCompZScore",true,...
			"ShowRaw",true,...
			"ShowZScore",true,...
			"ShowSubIDs",SHOW_SUBIDS)
	end
end
if SHOW_TRANSFORMED
	if SHOW_TIMING
		RobotResults2.PlotDotLine(data, ...
			"c_" + ["DET", "IDN", "ONB", "OCL"]' + "_Spd_lmn", ...
			data.Session == 1, ...
			"VarNames", ["DET", "IDN", "ONB", "OCL"],...
			"Title", "CogState Timing Measures",...
			"XLabel", "Reaction Time [log10(ms)]",...
			"ShowCompZScore",true,...
			"ShowRaw",false,...
			"ShowZScore",true,...
			"ShowSubIDs",SHOW_SUBIDS)
	end
	if SHOW_ACCURACY
		RobotResults2.PlotDotLine(data, ...
			"c_" + ["DET", "IDN", "ONB", "OCL"]' + "_Acc_asr", ...
			data.Session == 1, ...
			"VarNames", ["DET", "IDN", "ONB", "OCL"],...
			"Title", 'CogState Accuracy Measures',...
			"XLabel", "Response Accuracy [asin(sqrt(% Correct))]",...
			"ShowCompZScore",true,...
			"ShowRaw",false,...
			"ShowZScore",true,...
			"ShowSubIDs",SHOW_SUBIDS)
	end
end

% SCAT Sum
if SHOW_SCAT_SUM
	RobotResults2.PlotDotLine(data, ...
		"scat_Sum", ...
		data.Session == 1, ...
		"VarNames", "SCAT Sum",...
		"title", 'SCAT Sum',...
		"XLabel", "Symptom Sum",...
		"ShowRaw",true,...
		"ShowCompZScore",false,...
		"ShowZScore",false,...
		"ShowSubIDs",SHOW_SUBIDS)
end
if SHOW_SCAT_COUNT
	RobotResults2.PlotDotLine(data, ...
		"scat_Count", ...
		data.Session == 1, ...
		"VarNames", "SCAT Count",...
		"title", 'SCAT Number of Symptoms',...
		"XLabel", "Number of Symptoms (out of 22)",...
		"ShowRaw",true,...
		"ShowCompZScore",false,...
		"ShowZScore",false,...
		"ShowSubIDs",SHOW_SUBIDS)
end
if SHOW_DAYS_POST_INJRY
    RobotResults2.PlotDotLine(data, ...
		"DaysPostInjury", ...
		data.Session == 1, ...
		"VarNames", "Days Post Injury",...
		"title", 'Days Post Injury',...
		"XLabel", "Days",...
		"ShowRaw",true,...
		"ShowCompZScore",false,...
		"ShowZScore",false,...
		"ShowSubIDs",SHOW_SUBIDS)
end

